[tool.poetry]
name = "hw2"
version = "0.1.0"
description = ""
authors = ["tapyu"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
scipy = "^1.6.3"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
